require('plugins.packer')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.lualine')
require('plugins.neozoom')
require('plugins.tint')
require('plugins.gitsigns')
require('plugins.toggleterm')
